wordpress:
 container_name: wordpress
 image: wordpress
 links:
   - mariadb:mysql
 ports:
   - "8080:80"
mariadb:
 container_name: mariadb
 image: mariadb
 environment:
   MYSQL_ROOT_PASSWORD: example
phpmyadmin:
 container_name: phpmyadmin
 image: corbinu/docker-phpmyadmin
 links:
   - mariadb:mysql
 ports:
   - "8181:80"
 environment:
   MYSQL_USERNAME: root
   MYSQL_ROOT_PASSWORD: examplepass
